version: '3'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - "./:/app/"
    command:
      [
        "streamlit",
        "run",
        "app.py",
        "--server.enableCORS=false",
        "--server.enableWebsocketCompression=false"
      ]
